export const mockCategories = [
  {
    name: "Electronics",
    slug: "electronics",
    description: "Phones, laptops, tablets, headphones, and electronic accessories",
  },
  {
    name: "Clothing",
    slug: "clothing",
    description: "T-shirts, jackets, jeans, dresses, and apparel",
  },
  {
    name: "Shoes",
    slug: "shoes",
    description: "Sneakers, boots, sandals, formal shoes, and footwear",
  },
  {
    name: "Home & Kitchen",
    slug: "home-kitchen",
    description: "Cookware, bedding, furniture, and home decor",
  },
  {
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    description: "Fitness equipment, camping gear, and activewear",
  },
  {
    name: "Beauty & Personal Care",
    slug: "beauty-personal-care",
    description: "Skincare, makeup, grooming tools, and personal care products",
  },
  {
    name: "Books",
    slug: "books",
    description: "Fiction, non-fiction, textbooks, and comics",
  },
  {
    name: "Toys & Games",
    slug: "toys-games",
    description: "Board games, video games, educational toys, and gaming consoles",
  },
];

export const mockProducts = [
  // Electronics - Phones, laptops, headphones, tablets
  {
    name: "Apple iPhone 15 Pro Max, 256GB, Titanium Design with A17 Pro Chip and 48MP Camera System with 5x Optical Zoom",
    brand: "Apple",
    description: "Features the powerful A17 Pro chip with 6-core CPU and advanced camera system. Triple-camera setup includes 48MP main sensor with 5x optical zoom telephoto lens. Aerospace-grade titanium design with Ceramic Shield front. All-day battery life with up to 29 hours video playback. 5G capable with eSIM support. Available in 256GB, 512GB, and 1TB storage options.",
    price: 1199.99,
    category: "Electronics",
  },
  {
    name: "Apple MacBook Air 13.6-inch Laptop with M3 Chip, 8-Core CPU, 10-Core GPU, 18 Hours Battery Life, Silver",
    brand: "Apple",
    description: "13.6-inch Liquid Retina display with 500 nits brightness and P3 wide color. Apple M3 chip with 8-core CPU and 10-core GPU delivers exceptional performance. Up to 18 hours battery life for all-day productivity. Fanless design for silent operation. 1080p FaceTime HD camera and three-mic array. Two Thunderbolt ports and MagSafe 3 charging. Weighs just 2.7 pounds.",
    price: 1299.99,
    category: "Electronics",
  },
  {
    name: "Sony WH-1000XM5 Wireless Premium Noise Canceling Headphones with 30-Hour Battery Life and LDAC Audio, Black",
    brand: "Sony",
    description: "Industry-leading noise cancellation with Auto NC Optimizer. Eight microphones and dual processors for exceptional call quality. 30-hour battery life with quick charging (3 min charge = 3 hours playback). LDAC and DSEE Extreme for premium audio quality. Speak-to-Chat technology automatically pauses music. Ultra-comfortable synthetic leather cushions. Multipoint connection for seamless device switching.",
    price: 399.99,
    category: "Electronics",
  },
  {
    name: "Apple iPad Pro 12.9-inch Tablet with M2 Chip, Liquid Retina XDR Display, 12MP Camera, Face ID, Wi-Fi 6E",
    brand: "Apple",
    description: "12.9-inch Liquid Retina XDR display with ProMotion, True Tone, and P3 wide color. Apple M2 chip with 8-core CPU and 10-core GPU. 12MP Wide camera with Smart HDR 4 and 4K video. Apple Pencil (2nd generation) support with hover. Face ID for secure authentication. Wi-Fi 6E and optional 5G connectivity. Available with up to 2TB storage.",
    price: 1099.99,
    category: "Electronics",
  },
  {
    name: "Samsung Galaxy S24 Ultra 5G Smartphone with Built-in S Pen, 200MP Camera, 6.8-inch Display, Titanium Frame",
    brand: "Samsung",
    description: "6.8-inch Dynamic AMOLED 2X display with 120Hz adaptive refresh rate. Quad camera system with 200MP main sensor and 100x Space Zoom. Snapdragon 8 Gen 3 processor with 12GB RAM. Integrated S Pen stylus for precision input. 5000mAh battery with 45W fast charging. Titanium frame with Gorilla Glass Armor. Galaxy AI features for enhanced productivity.",
    price: 1299.99,
    category: "Electronics",
  },
  {
    name: "Dell XPS 15 Laptop, 15.6-inch 3.5K OLED Touchscreen, Intel Core i7, NVIDIA RTX 4060, 16GB RAM, 1TB SSD",
    brand: "Dell",
    description: "15.6-inch 3.5K OLED touchscreen with 100% DCI-P3 color gamut. 13th Gen Intel Core i7 processor with 16GB DDR5 RAM. NVIDIA GeForce RTX 4060 graphics with 8GB GDDR6. 1TB PCIe Gen 4 SSD storage. Precision machined aluminum chassis. FHD+ webcam with Windows Hello. Up to 13 hours battery life. Thunderbolt 4 and USB-C ports.",
    price: 1899.99,
    category: "Electronics",
  },
  {
    name: "Apple AirPods Pro 2nd Generation Wireless Earbuds with Adaptive Audio, Active Noise Cancellation, MagSafe Case",
    brand: "Apple",
    description: "Upgraded H2 chip delivers twice the noise cancellation. Adaptive Audio dynamically adjusts noise control. Personalized spatial audio with dynamic head tracking. Four pairs of silicone tips for customizable fit. Up to 6 hours listening time, 30 hours with MagSafe charging case. Touch control for volume adjustment. Conversation Awareness lowers media when you speak. IPX4 sweat and water resistant.",
    price: 249.99,
    category: "Electronics",
  },
  {
    name: "Amazon Kindle Paperwhite 6.8-inch E-Reader with 300 PPI Glare-Free Display, Adjustable Warm Light, Waterproof IPX8, 16GB",
    brand: "Amazon",
    description: "6.8-inch high-resolution 300 ppi display reads like real paper. Adjustable warm light for comfortable reading day or night. IPX8 waterproof rating safe for beach and bath. Weeks of battery life on a single charge. 16GB storage holds thousands of books. USB-C charging with optional wireless charging. Dark mode for reading in low light. Free cloud storage for Amazon content.",
    price: 139.99,
    category: "Electronics",
  },
  {
    name: "Google Pixel 8 Pro 5G Smartphone with AI-Powered Camera, 6.7-inch OLED Display, Tensor G3 Chip, 128GB",
    brand: "Google",
    description: "6.7-inch LTPO OLED display with 120Hz refresh rate. Google Tensor G3 chip with Titan M2 security. Advanced camera system with 50MP main, 48MP telephoto, and 48MP ultrawide. Magic Editor and Best Take AI photo features. Video Boost for enhanced video quality. Face Unlock and fingerprint sensor. 7 years of OS and security updates. All-day battery with fast wireless charging.",
    price: 999.99,
    category: "Electronics",
  },
  {
    name: "Bose QuietComfort Earbuds II True Wireless with Personalized Noise Cancellation, CustomTune Technology, IPX4",
    brand: "Bose",
    description: "CustomTune technology analyzes your ears for optimized sound. World-class noise cancellation with Aware Mode. Three sizes of ear tips and stability bands for secure fit. Up to 6 hours battery life, 24 hours with charging case. Advanced Bluetooth 5.3 with multipoint connection. Touch controls for music, calls, and ANC modes. IPX4 water resistance. Simple Sound app for customization.",
    price: 299.99,
    category: "Electronics",
  },

  // Clothing - T-shirts, jackets, jeans, dresses
  {
    name: "Everlane Classic Crew Neck T-Shirt, 100% Organic Cotton, Relaxed Fit, Pre-Shrunk, White",
    brand: "Everlane",
    description: "Made from premium organic cotton that gets softer with every wash. Relaxed fit with reinforced shoulder seams for durability. Ribbed crew neckline holds its shape. Pre-shrunk fabric prevents size changes after washing. Tagless label for maximum comfort. Side-seam construction eliminates twisting. Available in sizes XS-XXL. Machine washable for easy care.",
    price: 24.99,
    category: "Clothing",
  },
  {
    name: "Schott NYC Classic Bomber Jacket, Genuine Leather, Ribbed Cuffs and Waistband, Quilted Lining, Brown",
    brand: "Schott NYC",
    description: "Full-grain cowhide leather ages beautifully over time. Iconic bomber silhouette with ribbed cuffs and waistband. Polyester fill lining provides warmth without bulk. Two front slash pockets and interior pocket. Snap-front closure with metal zipper. Quilted satin lining in sleeve. Leather is hand-finished for unique character. Professional leather care recommended.",
    price: 299.99,
    category: "Clothing",
  },
  {
    name: "Levi's 511 Slim Fit Jeans for Men, Stretch Denim with Fade-Resistant Wash, Dark Indigo, 32W x 32L",
    brand: "Levi's",
    description: "Premium stretch denim with 2% elastane for flexibility. Slim through hip and thigh with slight taper at leg. Fade-resistant dark indigo wash maintains color. Five-pocket styling with signature arcuate stitching. Button fly with metal rivets at stress points. Mid-rise waist sits just below natural waistline. Machine washable with color-safe treatment. Available in 28-38 waist sizes.",
    price: 79.99,
    category: "Clothing",
  },
  {
    name: "Reformation Floral Midi Dress with Adjustable Straps, Smocked Back Panel, Sustainable Viscose, Summer Print",
    brand: "Reformation",
    description: "Made from sustainable viscose with botanical floral pattern. Flattering midi length with flowing A-line silhouette. Adjustable spaghetti straps for customizable fit. Smocked back panel creates comfortable stretch. Side seam pockets for convenience. Lined bodice with unlined skirt. Button-front closure from neckline to waist. Perfect for warm weather occasions.",
    price: 89.99,
    category: "Clothing",
  },
  {
    name: "Urban Outfitters Vintage Graphic T-Shirt, Oversized Fit with Band Graphics, Cotton-Poly Blend, Retro Wash",
    brand: "Urban Outfitters",
    description: "Super soft cotton-polyester blend with vintage wash. Oversized fit with dropped shoulders for relaxed look. Screen-printed retro band graphics with distressed finish. Ribbed crew neckline with raw edge detail. Longer length perfect for tucking or leaving loose. Pre-washed for immediate softness. Unisex sizing runs large for intentional oversized fit. Machine wash cold.",
    price: 34.99,
    category: "Clothing",
  },
  {
    name: "The North Face Puffer Jacket with 600-Fill Down Insulation, Water-Resistant Shell, Removable Hood, Black",
    brand: "The North Face",
    description: "600-fill responsibly sourced down insulation provides superior warmth. DWR finish repels water and snow. Removable hood with adjustable drawcord. Secure-zip hand pockets and interior media pocket. Elastic-bound cuffs seal out cold. Two-way front zip for ventilation control. Packable design stuffs into its own pocket. Recycled materials reduce environmental impact.",
    price: 179.99,
    category: "Clothing",
  },
  {
    name: "AGOLDE Black Skinny Jeans for Women, High-Stretch Denim with Recovery, High-Rise Waist, Coated Finish",
    brand: "AGOLDE",
    description: "High-stretch denim with recovery keeps shape all day. Skinny fit from hip through ankle. Deep black color with tonal stitching. High-rise waist at 10.5 inches. Five-pocket construction with zip fly. Coated finish adds subtle sheen and texture. Stretch fabric moves with you. Professional styling works for office or weekend. Machine washable in cold water.",
    price: 69.99,
    category: "Clothing",
  },
  {
    name: "Adrianna Papell Evening Dress, Floor-Length with Satin Finish, V-Neckline, A-Line Silhouette, Navy Blue",
    brand: "Adrianna Papell",
    description: "Luxurious satin fabric with subtle sheen drapes beautifully. Floor-length silhouette with A-line skirt. Flattering V-neckline elongates the torso. Hidden back zipper for seamless look. Boned bodice provides structure and support. Fully lined for comfort and opacity. Side pockets hidden in seams. Ideal for weddings, galas, and formal events. Dry clean only.",
    price: 149.99,
    category: "Clothing",
  },
  {
    name: "J.Crew Button-Down Shirt with Classic Stripes, 100% Cotton Poplin, Slim Fit, Navy and White",
    brand: "J.Crew",
    description: "100% cotton poplin fabric is crisp yet breathable. Classic navy and white horizontal stripes. Slim fit with slightly tapered waist. Button-down collar for versatile styling. Single chest pocket for small essentials. Split back yoke for comfortable movement. Rounded hem can be tucked or untucked. Machine washable, wrinkle-resistant with proper care.",
    price: 49.99,
    category: "Clothing",
  },
  {
    name: "Wrangler Denim Jean Jacket, 100% Cotton with Vintage Wash, Trucker Style, Metal Buttons, Medium Blue",
    brand: "Wrangler",
    description: "Classic 100% cotton denim in medium vintage wash. Traditional trucker jacket silhouette. Point collar with button-front closure. Two chest pockets with button flaps. Side entry pockets at waist. Adjustable button tabs at sides for custom fit. Metal shank buttons throughout. Pre-washed for softness and minimal shrinkage. True to size classic fit.",
    price: 89.99,
    category: "Clothing",
  },

  // Shoes - Sneakers, boots, sandals, formal shoes
  {
    name: "Nike Air Max 270 Running Shoes with Max Air Cushioning, Breathable Mesh Upper, Rubber Outsole, Black/White",
    brand: "Nike",
    description: "Large Max Air unit in heel provides exceptional cushioning. Breathable mesh upper with synthetic overlays for support. Foam midsole delivers lightweight responsive comfort. Rubber outsole with waffle pattern for traction. Pull tabs on tongue and heel for easy on/off. Reflective details enhance visibility. Available in men's and women's sizes. Ideal for running and everyday wear.",
    price: 149.99,
    category: "Shoes",
  },
  {
    name: "Timberland Classic 6-Inch Waterproof Boots, Premium Leather, Anti-Fatigue Footbed, Padded Collar, Wheat",
    brand: "Timberland",
    description: "Premium full-grain waterproof leather uppers. Seam-sealed construction keeps feet dry in wet conditions. Padded collar provides ankle support and comfort. Anti-fatigue technology footbed for all-day comfort. Durable rubber lug outsole for superior traction. Rustproof speed lace hardware with lace hooks. Fully gusseted tongue keeps out debris. Iconic yellow boot design since 1973.",
    price: 199.99,
    category: "Shoes",
  },
  {
    name: "Birkenstock Arizona Sandals with Cork-Latex Footbed, Adjustable Straps, Suede Lining, Taupe",
    brand: "Birkenstock",
    description: "Anatomically shaped cork-latex footbed molds to your feet. Soft suede footbed lining wicks away moisture. Two adjustable straps with metal buckles. Contoured footbed with arch support and deep heel cup. EVA sole is lightweight and flexible. Raised toe bar encourages natural gripping motion. Available in regular and narrow widths. Made in Germany with quality craftsmanship.",
    price: 99.99,
    category: "Shoes",
  },
  {
    name: "Cole Haan Captoe Oxford Dress Shoes, Full-Grain Leather, Grand.ØS Technology, Memory Foam Footbed, Black",
    brand: "Cole Haan",
    description: "Full-grain leather upper with traditional captoe detail. Grand.ØS technology provides flexibility and cushioning. Memory foam footbed with arch support. Rubber sole with forefoot flex grooves. Leather lining and sock lining. Traditional lace-up closure with five eyelets. Stacked heel adds subtle height. Perfect for office, interviews, and special occasions. Available in black and brown.",
    price: 129.99,
    category: "Shoes",
  },
  {
    name: "Adidas Ultraboost 22 Running Shoes with Boost Cushioning, Primeknit+ Upper, Continental Rubber Outsole, Women's",
    brand: "Adidas",
    description: "Responsive Boost midsole returns energy with every step. Primeknit+ upper adapts to foot shape for custom fit. Linear Energy Push system increases running efficiency. Continental rubber outsole provides superior grip. Torsion System between heel and forefoot. Supportive heel counter for stability. Reflective details for low-light visibility. Designed specifically for female biomechanics.",
    price: 189.99,
    category: "Shoes",
  },
  {
    name: "Dr. Martens 1460 Boots, 8-Eye Leather with AirWair Sole, Yellow Stitching, Goodyear Welt Construction, Black",
    brand: "Dr. Martens",
    description: "Durable Smooth leather upper develops unique patina. Classic 8-eye lace-up design with yellow stitching. Air-cushioned sole provides comfort and shock absorption. Goodyear welt construction for durability. Grooved sides for classic Doc's look. Scripted heel loop. Heel-loop and yellow stitching. Made with classic Doc's DNA. Break-in period creates personalized fit.",
    price: 169.99,
    category: "Shoes",
  },
  {
    name: "Havaianas Flip Flops, 100% Rubber Construction, Rice Grain Pattern Footbed, Thong Style, Vibrant Colors",
    brand: "Havaianas",
    description: "100% rubber construction resists water and odor. Rice grain pattern footbed provides grip. Cushioned footbed absorbs impact. Thong-style strap with embossed logo. Textured sole prevents slipping. Made in Brazil with proprietary rubber formula. Won't lose shape or flatten over time. Available in dozens of vibrant colors. Perfect for beach, pool, or casual summer wear.",
    price: 29.99,
    category: "Shoes",
  },
  {
    name: "Sperry Leather Penny Loafers with Hand-Sewn Moccasin Construction, Memory Foam Footbed, Non-Marking Rubber Sole, Brown",
    brand: "Sperry",
    description: "Genuine leather upper with hand-sewn moccasin construction. Iconic penny keeper strap across vamp. Cushioned footbed with memory foam. Shock-absorbing EVA heel cup. Non-marking rubber outsole with Wave-Siping for traction. Leather sock lining wicks moisture. Easy slip-on style with no-tie convenience. Versatile enough for business casual or smart casual. Available in various leather finishes.",
    price: 119.99,
    category: "Shoes",
  },
  {
    name: "Converse Chuck Taylor All Star Classic Canvas Sneakers, Rubber Toe Cap, OrthoLite Cushioning, Low Top, Black",
    brand: "Converse",
    description: "Durable canvas upper in classic silhouette. Iconic rubber toe cap and toe bumper. Medial eyelets enhance airflow. OrthoLite cushioning for all-day comfort. Original Chuck Taylor ankle patch. Diamond pattern outsole for traction. Vulcanized rubber sole construction. Available in high-top and low-top styles. Over 100 years of authentic style. Unisex sizing.",
    price: 64.99,
    category: "Shoes",
  },
  {
    name: "Blundstone Ankle Chelsea Boots with Elastic Side Panels, Premium Leather, XRD Technology Footbed, Water-Resistant",
    brand: "Blundstone",
    description: "Premium leather upper with water-resistant finish. Elastic side gussets for easy on/off. Contoured comfort footbed with XRD Technology. Shock Protection System in heel. Thermoplastic polyurethane outsole resists oil and acid. Steel shank for structural support. Lightweight design won't weigh you down. Pull tabs for easy entry. Suitable for all-day wear in any weather.",
    price: 139.99,
    category: "Shoes",
  },

  // Home & Kitchen - Cookware, bedding, furniture, decor
  {
    name: "Le Creuset Enameled Cast Iron Dutch Oven, 5.5 Quart with Tight-Fitting Lid, Oven Safe to 500°F, Cherry Red",
    brand: "Le Creuset",
    description: "Cast iron construction provides superior heat distribution and retention. Colorful porcelain enamel requires no seasoning. Interior enamel resists staining and dulling. Tight-fitting lid retains heat, moisture and flavor. Large handles for secure grip. Perfect for slow cooking, braising, baking bread and more. Oven safe to 500°F. Smooth enamel interior cleans easily. Lifetime warranty. Made in France.",
    price: 349.99,
    category: "Home & Kitchen",
  },
  {
    name: "Parachute Egyptian Cotton Sheet Set, 800 Thread Count Percale Weave, Deep Pocket Fitted Sheet, Queen, White",
    brand: "Parachute",
    description: "100% long-staple Egyptian cotton for ultimate softness. Percale weave is crisp, cool and breathable. 800 thread count for luxury hotel quality. Deep pocket fitted sheet fits mattresses up to 17 inches. Set includes flat sheet, fitted sheet and two pillowcases. OEKO-TEX certified free from harmful chemicals. Gets softer with every wash. Available in Queen, King, and Cal King.",
    price: 149.99,
    category: "Home & Kitchen",
  },
  {
    name: "Article Mid-Century Modern Sofa, 3-Seater with Tufted Cushions, Solid Walnut Legs, Polyester Upholstery, 78 inches",
    brand: "Article",
    description: "Solid walnut legs with angled design. Durable polyester upholstery in multiple color options. Tufted cushions with high-density foam core. Removable cushion covers with hidden zippers. Hardwood frame construction for lasting durability. Low profile design suits modern and traditional spaces. Assembly required with included tools and instructions. Seats three adults comfortably. 78 inches wide.",
    price: 899.99,
    category: "Home & Kitchen",
  },
  {
    name: "Society6 Bohemian Wall Tapestry with Mandala Design, Woven Polyester, Includes Hanging Hardware, Large 88x104 inches",
    brand: "Society6",
    description: "Vibrant colors printed on lightweight woven polyester. Intricate mandala pattern with boho aesthetic. Multiple sizes available from small to extra large. Includes wooden dowel and string for hanging. Machine washable for easy care. Fade-resistant dyes maintain color vibrancy. Double-sided print option available. Perfect for bedroom, living room, or dorm. Transform any blank wall into art.",
    price: 39.99,
    category: "Home & Kitchen",
  },
  {
    name: "Cuisinart Stainless Steel Cookware Set, 12-Piece with Glass Lids, Aluminum Core, Induction Compatible, Dishwasher Safe",
    brand: "Cuisinart",
    description: "Premium stainless steel with aluminum core for even heating. Mirror finish exterior won't discolor or react with food. Tapered rim for drip-free pouring. Cool Grip handles stay cool on stovetop. Tempered glass lids let you monitor cooking. Measurement markings on cookware interiors. Induction compatible works on all stovetops. Oven safe to 500°F. Dishwasher safe for easy cleanup. Includes 1.5-qt and 3-qt saucepans, 8-qt stockpot, 8-in and 10-in skillets, and steamer insert.",
    price: 299.99,
    category: "Home & Kitchen",
  },
  {
    name: "Coop Home Goods Memory Foam Pillow Set of 2, Adjustable Shredded Fill with Gel, Bamboo Cover, Queen Size",
    brand: "Coop Home Goods",
    description: "Adjustable fill lets you customize loft and firmness. Shredded memory foam with gel-infused pieces. Bamboo-derived rayon cover is soft and breathable. Hypoallergenic materials resist dust mites. CertiPUR-US certified foam is safe and non-toxic. Machine washable cover with zipper access. Designed for all sleep positions. Set includes two queen-size pillows. 5-year warranty included.",
    price: 79.99,
    category: "Home & Kitchen",
  },
  {
    name: "West Elm Rustic Reclaimed Wood Coffee Table with Metal Frame, Lower Shelf, Water-Based Finish, 48x24 inches",
    brand: "West Elm",
    description: "Reclaimed pine wood top with natural variations and knots. Powder-coated metal frame in matte black finish. Lower shelf provides additional storage space. Water-based finish protects wood while showing grain. Each piece is unique due to reclaimed materials. Supports up to 150 pounds on top surface. Easy assembly with included hardware. 48 inches wide by 24 inches deep. Pairs well with industrial or farmhouse decor.",
    price: 249.99,
    category: "Home & Kitchen",
  },
  {
    name: "CB2 Ceramic Vase Collection, Set of 3 Minimalist Vases in Graduated Sizes, Matte White Finish, Handcrafted",
    brand: "CB2",
    description: "Modern cylindrical silhouettes in graduated sizes. Matte white ceramic finish complements any decor. Small, medium, and large vases for varied arrangements. Waterproof ceramic holds fresh flowers. Wide openings accommodate full bouquets. Weighted bases provide stability. Handcrafted with subtle variations. Group together for impact or display separately. Ideal for mantel, dining table, or entryway.",
    price: 59.99,
    category: "Home & Kitchen",
  },
  {
    name: "GreenPan Non-Stick Frying Pan Set, Ceramic-Coated 8-inch and 10-inch, Diamond-Reinforced, PFAS-Free, Dishwasher Safe",
    brand: "GreenPan",
    description: "Healthy ceramic nonstick coating free of PFAS, PFOA, lead, and cadmium. Hard anodized aluminum body conducts heat efficiently. Diamond-reinforced coating for extra durability. Oven safe up to 600°F. Stainless steel handles with stay-cool coating. Set includes 8-inch and 10-inch frying pans. Suitable for all stovetops except induction. Dishwasher safe but hand washing recommended. Scratch-resistant surface.",
    price: 89.99,
    category: "Home & Kitchen",
  },
  {
    name: "Pottery Barn Quilted Bedspread, 100% Cotton Reversible Coverlet with Diamond Pattern, Matching Shams, Queen, Ivory",
    brand: "Pottery Barn",
    description: "100% cotton face and back in complementary colors. Classic diamond quilting pattern adds texture. Generously sized to drape over mattress edges. Reversible design offers two styling options. Matching standard shams included (2 for Queen/King). Pre-washed for softness and minimal shrinkage. Machine washable in cold water. Available in Full/Queen and King sizes. Coordinates with various bedroom styles.",
    price: 119.99,
    category: "Home & Kitchen",
  },

  // Sports & Outdoors - Fitness equipment, camping gear, activewear
  {
    name: "Bowflex SelectTech Adjustable Dumbbells, 5-52.5 lbs per Dumbbell, Quick-Select Dial System, Space-Saving with Trays",
    brand: "Bowflex",
    description: "Adjusts from 5 to 52.5 pounds per dumbbell. Turn dial to select desired weight. Replaces 15 sets of traditional dumbbells. Durable molding around metal plates reduces noise. Compact design fits in small spaces. Weight plates included secure on dumbbell handles. Each dumbbell adjusts in 2.5-pound increments. Includes storage trays for organization. Two-year warranty on parts.",
    price: 399.99,
    category: "Sports & Outdoors",
  },
  {
    name: "Coleman 4-Person Camping Tent with WeatherTec System, Waterproof Dome Design, Easy 10-Minute Setup, 9x7 feet",
    brand: "Coleman",
    description: "WeatherTec system with patented welded floors and sealed seams. Sets up in 10 minutes with snag-free continuous pole sleeves. Large front door with zippered mesh screen. Ground vent and mesh roof for improved airflow. E-Port allows electrical cord access. Interior storage pockets keep gear organized. Measures 9 x 7 feet with 59-inch center height. Included rainfly provides extra weather protection. Fits one queen airbed.",
    price: 159.99,
    category: "Sports & Outdoors",
  },
  {
    name: "Lululemon Align High-Waist Yoga Pants, Nulu Fabric with Four-Way Stretch, Hidden Pocket, Squat-Proof, 25 inch",
    brand: "Lululemon",
    description: "Nulu fabric feels buttery-soft and weightless. Four-way stretch moves with you. High-rise waistband for comfortable coverage. Hidden waistband pocket for cards and keys. Squat-proof fabric provides total coverage. Sweat-wicking and quick-drying. Seamless construction reduces chafing. Flat seams and gusset for comfort. Available in 7/8, full-length, and cropped styles. Multiple inseam lengths offered.",
    price: 49.99,
    category: "Sports & Outdoors",
  },
  {
    name: "Manduka PRO Yoga Mat, 6mm Thick with Non-Slip Surface, Alignment Stripes, Eco-Friendly, 71x24 inches, Lifetime Guarantee",
    brand: "Manduka",
    description: "6mm thick cushioning supports joints during practice. Closed-cell surface prevents sweat from seeping in. Non-slip surface on both sides. Alignment stripes assist with positioning. Eco-friendly materials free from harmful chemicals. Lightweight yet durable construction. Easy to clean with mild soap. Includes carrying strap for transport. Measures 71 inches long by 24 inches wide. Lifetime guarantee.",
    price: 39.99,
    category: "Sports & Outdoors",
  },
  {
    name: "REI Co-op 3-Season Sleeping Bag, Mummy Shape with Hood, Synthetic Insulation, Rated to 20°F, Compression Sack",
    brand: "REI Co-op",
    description: "Synthetic insulation performs even when wet. Mummy shape with hood reduces heat loss. Temperature rating comfort to 32°F, lower limit 20°F. Water-resistant shell fabric sheds moisture. Two-way zipper allows temperature regulation. Draft tube prevents cold air infiltration. Includes compression stuff sack for compact storage. Fits users up to 6 feet tall. Machine washable for easy care.",
    price: 79.99,
    category: "Sports & Outdoors",
  },
  {
    name: "TheraBand Resistance Bands Set, 5 Progressive Levels with Handles, Door Anchor, Ankle Straps, Exercise Guide",
    brand: "TheraBand",
    description: "Five bands with progressive resistance levels (X-Light to X-Heavy). Natural latex rubber provides smooth consistent resistance. Cushioned foam handles for comfortable grip. Door anchor attaches to any door frame. Ankle straps for lower body exercises. Includes carry bag for portability. Exercise guide with illustrated workouts. Stackable bands for increased resistance. Suitable for strength training, physical therapy, and rehab.",
    price: 29.99,
    category: "Sports & Outdoors",
  },
  {
    name: "Osprey Hiking Backpack 40L with Adjustable Suspension, AirScape Back Panel, Hydration Compatible, Integrated Raincover",
    brand: "Osprey",
    description: "AirScape back panel with ridged foam for ventilation. Adjustable torso length fits range of body sizes. Integrated raincover deploys from bottom compartment. Stow-on-the-Go trekking pole attachment. Dual zippered hipbelt pockets for quick access. Side mesh pockets for water bottles. Hydration reservoir sleeve with port. Front panel organization pocket. Sleeping bag compartment with removable divider. Available in multiple colors.",
    price: 129.99,
    category: "Sports & Outdoors",
  },
  {
    name: "Nike Dri-FIT Running Shorts for Men, Lightweight with Built-in Liner, Zippered Pocket, Reflective Elements, 7-inch",
    brand: "Nike",
    description: "Dri-FIT technology wicks sweat away from skin. Lightweight woven fabric allows freedom of movement. Built-in mesh brief provides support. Elastic waistband with internal drawcord. Zippered back pocket secures small items. Reflective elements enhance low-light visibility. Split hem design increases stride length. Standard fit is relaxed through hips and thighs. 7-inch inseam. Available in men's sizes S-XXL.",
    price: 34.99,
    category: "Sports & Outdoors",
  },
  {
    name: "Rogue Fitness Cast Iron Kettlebell, 25 lbs with Wide Handle, Flat Bottom, Powder Coat Finish for Grip",
    brand: "Rogue Fitness",
    description: "Single-cast construction eliminates weak points. Wide handle accommodates two-handed grips. Flat bottom allows upright storage. Powder coat finish provides excellent grip. Smooth finish won't damage floors. Weight is clearly marked. Perfect for swings, Turkish get-ups, and snatches. Builds functional strength and cardiovascular endurance. Available in weights from 9 to 106 pounds.",
    price: 44.99,
    category: "Sports & Outdoors",
  },
  {
    name: "MSR Portable Camping Stove with WindBurner Technology, Piezo Igniter, Compact Design, Hard-Sided Case",
    brand: "MSR",
    description: "WindBurner technology shields flame from wind. Piezo igniter provides reliable push-button start. Adjustable heat control from simmer to boil. Compact design packs small in backpack. Compatible with standard propane canisters. Pot support accommodates various cookware sizes. Boils 1 liter of water in 4.5 minutes. Weighs only 14 ounces. Includes hard-sided carrying case.",
    price: 59.99,
    category: "Sports & Outdoors",
  },

  // Beauty & Personal Care - Skincare, makeup, grooming tools
  {
    name: "SkinCeuticals C E Ferulic Serum with 20% Vitamin C, Ferulic Acid, Vitamin E, Anti-Aging Antioxidant, 1 oz",
    brand: "SkinCeuticals",
    description: "20% L-ascorbic acid in stable formula. Ferulic acid and vitamin E boost antioxidant protection. Neutralizes free radicals from environmental damage. Improves appearance of fine lines and wrinkles. Brightens skin tone and reduces dark spots. Once-daily application delivers visible results. Suitable for normal, dry, and sensitive skin. 1 oz bottle lasts approximately 3 months. Apply in morning before moisturizer.",
    price: 29.99,
    category: "Beauty & Personal Care",
  },
  {
    name: "Urban Decay Naked Eyeshadow Palette, 12 Neutral Shades with Matte and Shimmer Finishes, Includes Mirror and Brush",
    brand: "Urban Decay",
    description: "Mix of matte, satin, and shimmer finishes. Highly pigmented formula blends easily. Long-lasting wear up to 12 hours. Includes full-size mirror in compact. Buildable coverage from sheer to opaque. Creamy texture glides on smoothly. Shades range from light vanilla to deep espresso. Cruelty-free and vegan formula. Includes dual-ended brush for application. Perfect for everyday looks and special occasions.",
    price: 44.99,
    category: "Beauty & Personal Care",
  },
  {
    name: "Philips Norelco Electric Beard Trimmer, Cordless with 20 Length Settings, Titanium Blades, 90-Minute Runtime, USB Charging",
    brand: "Philips Norelco",
    description: "Self-sharpening titanium blades stay sharp longer. 20 built-in length settings from 0.5 to 10mm. 90 minutes runtime on full charge. Lithium-ion battery for consistent power. Fully washable for easy cleaning under tap. Rounded blade tips prevent skin irritation. Zoom wheel adjusts length in 0.5mm increments. Includes detachable stubble comb. USB charging with power adapter. One-year warranty.",
    price: 69.99,
    category: "Beauty & Personal Care",
  },
  {
    name: "CeraVe Retinol Night Cream with Encapsulated Retinol, Ceramides, Hyaluronic Acid, Anti-Aging Moisturizer, 1.7 oz",
    brand: "CeraVe",
    description: "Encapsulated retinol minimizes irritation while maximizing benefits. Three essential ceramides restore skin barrier. Hyaluronic acid retains moisture. Niacinamide calms skin. Peptide complex supports natural collagen. Non-comedogenic won't clog pores. Fragrance-free and suitable for sensitive skin. MVE Technology provides 24-hour hydration. Developed with dermatologists. Apply to face and neck at bedtime.",
    price: 39.99,
    category: "Beauty & Personal Care",
  },
  {
    name: "MAC Matte Lipstick Set, Collection of 6 Long-Lasting Shades in Nude, Pink, Red, Berry, Iconic Packaging",
    brand: "MAC",
    description: "Intense matte finish in popular shades. Highly pigmented color in one stroke. Long-wearing formula lasts up to 8 hours. Creamy texture glides on smoothly. Non-drying formula with moisturizing ingredients. Includes nude, pink, red, and berry shades. Iconic MAC lipstick bullet packaging. Shades curated for versatile looks. Can be layered or blended. Suitable for all skin tones.",
    price: 54.99,
    category: "Beauty & Personal Care",
  },
  {
    name: "Clarisonic Sonic Facial Cleansing Brush, Waterproof with 3 Speed Settings, USB Rechargeable, Sensitive Brush Head",
    brand: "Clarisonic",
    description: "Sonic frequency oscillation removes impurities. Soft silicone bristles gentle on all skin types. Waterproof design safe for shower use. Three speed settings for customization. USB rechargeable battery lasts up to 300 uses. Removes makeup 6x better than hands alone. T-Timer pulses every 20 seconds. One-year warranty. Includes sensitive brush head and travel case. Dermatologist recommended.",
    price: 79.99,
    category: "Beauty & Personal Care",
  },
  {
    name: "Neutrogena Hydrating Face Mask Pack, 10 Sheet Masks with Hyaluronic Acid, Hydrogel Material, Individually Wrapped",
    brand: "Neutrogena",
    description: "100% hydrogel material adheres to face contours. Hyaluronic acid provides deep hydration. Natural botanical extracts soothe and nourish. Each mask contains full bottle of serum. Cooling sensation refreshes tired skin. Visible results in just 15 minutes. Dermatologist tested and hypoallergenic. Fragrance-free and alcohol-free. Individually wrapped for freshness. Use 2-3 times per week.",
    price: 24.99,
    category: "Beauty & Personal Care",
  },
  {
    name: "Dyson Supersonic Hair Dryer with Intelligent Heat Control, Ionic Technology, Includes 3 Attachments, Silver",
    brand: "Dyson",
    description: "Digital motor V9 spins at 110,000rpm. Air Multiplier technology amplifies airflow. Intelligent heat control prevents extreme heat damage. Negative ions reduce static and frizz. Four heat settings and three speed settings. Cool shot locks in hairstyle. Magnetic attachments easy to swap. Includes smoothing nozzle, styling concentrator, and diffuser. Lightweight ergonomic design. Fast drying without extreme heat.",
    price: 89.99,
    category: "Beauty & Personal Care",
  },
  {
    name: "La Roche-Posay Anthelios SPF 50 Face Sunscreen, Broad-Spectrum with Antioxidants, Blue Light Filter, Matte Finish, 1.7 oz",
    brand: "La Roche-Posay",
    description: "SPF 50 provides high UVA/UVB protection. Cell-Ox Shield antioxidant complex. Blue light filter protects from digital screens. Lightweight fluid texture absorbs quickly. Non-greasy matte finish works under makeup. Water resistant for 80 minutes. Fragrance-free and paraben-free. Suitable for sensitive skin. Dermatologist and pediatrician tested. Apply 15 minutes before sun exposure. Reapply every 2 hours.",
    price: 19.99,
    category: "Beauty & Personal Care",
  },
  {
    name: "Morphe Professional Makeup Brush Set, 15-Piece with Synthetic Bristles, Face and Eye Brushes, Leatherette Case",
    brand: "Morphe",
    description: "Ultra-soft synthetic bristles ideal for powder and cream. Ergonomic handles for comfortable control. Includes face brushes for foundation, powder, blush, contour. Eye brushes for shadow, liner, brow, blend. Brushes labeled with numbers for identification. Ferrules secure bristles to handles. Vegan and cruelty-free materials. Includes leatherette case for storage and travel. Hand wash with mild soap. Reshape and lay flat to dry.",
    price: 49.99,
    category: "Beauty & Personal Care",
  },

  // Books - Fiction, non-fiction, textbooks, comics
  {
    name: "The Midnight Library by Matt Haig, Bestselling Fiction Novel About Infinite Possibilities and Second Chances, Paperback 304 Pages",
    brand: "Penguin Random House",
    description: "Novel by Matt Haig exploring parallel lives and choices. Story follows Nora Seed between life and death. Each book in magical library shows different life path. Uplifting tale about self-acceptance and hope. International bestseller translated into 40+ languages. 304 pages in paperback format. Named one of best books of the year. Perfect for book clubs and discussions. Combines philosophy with engaging storytelling.",
    price: 16.99,
    category: "Books",
  },
  {
    name: "Atomic Habits by James Clear, Practical Guide to Building Good Habits and Breaking Bad Ones, 320 Pages, New York Times Bestseller",
    brand: "Penguin Random House",
    description: "James Clear's proven framework for habit formation. Four Laws of Behavior Change explained. Strategies based on neuroscience and psychology. Real-world examples and actionable advice. Helps break bad habits and build good ones. Over 10 million copies sold worldwide. 320 pages packed with insights. Includes habit tracker templates. Applicable to personal and professional goals. New York Times bestseller for years.",
    price: 18.99,
    category: "Books",
  },
  {
    name: "Calculus Early Transcendentals by James Stewart, 9th Edition College Textbook with WebAssign Access, 1300+ Pages",
    brand: "Cengage",
    description: "James Stewart's definitive calculus textbook, 9th edition. Clear explanations with step-by-step solutions. Thousands of practice problems with varying difficulty. Conceptual understanding emphasized alongside computation. Early transcendentals approach introduces exponential and logarithmic functions early. Includes WebAssign access for online homework. Full color illustrations and graphs. 1300+ pages covering single and multivariable calculus. Used in universities worldwide.",
    price: 249.99,
    category: "Books",
  },
  {
    name: "Calvin and Hobbes: Complete Collection by Bill Watterson, 3-Volume Hardcover Box Set, Full Color Comic Strips",
    brand: "Andrews McMeel",
    description: "Complete collection of beloved comic strip. All Calvin and Hobbes strips in chronological order. Three hardcover volumes in protective slipcase. Full-color restoration of original artwork. Over 1400 pages total of timeless humor. Features imaginative six-year-old Calvin and tiger Hobbes. Explores childhood, philosophy, and adventure. Winner of multiple awards including Reuben Award. Perfect for fans of all ages. Considered one of greatest comic strips ever.",
    price: 89.99,
    category: "Books",
  },
  {
    name: "Project Hail Mary by Andy Weir, Science Fiction Adventure Novel, Goodreads Choice Award Winner, 496 Pages, Hardcover",
    brand: "Penguin Random House",
    description: "From author of The Martian comes new space adventure. Lone astronaut must save Earth from extinction. Gripping blend of hard science and humor. Goodreads Choice Award winner for Science Fiction. 496 pages of edge-of-seat entertainment. Optioned for film starring Ryan Gosling. Perfect for fans of The Martian and sci-fi. Combines complex problem-solving with emotional depth. Fast-paced plot with surprising twists.",
    price: 17.99,
    category: "Books",
  },
  {
    name: "Sapiens: A Brief History of Humankind by Yuval Noah Harari, International Bestseller, 464 Pages, #1 New York Times Bestseller",
    brand: "HarperCollins",
    description: "Chronicles 70,000 years of human history. Examines cognitive, agricultural, and scientific revolutions. Questions everything we thought we knew about being human. Over 25 million copies sold in 60+ languages. 464 pages of accessible scholarship. Combines history, biology, philosophy, and economics. Thought-provoking perspective on humanity's future. Ideal for curious minds and critical thinkers. International phenomenon and #1 bestseller.",
    price: 19.99,
    category: "Books",
  },
  {
    name: "Organic Chemistry by David Klein, 4th Edition College Textbook with WileyPLUS Access, 1300+ Pages, Full Color",
    brand: "Wiley",
    description: "David Klein's student-friendly approach to organic chemistry, 4th edition. Skills-based pedagogy emphasizes problem-solving. Clear explanations of mechanisms and reactions. Over 2000 practice problems with solutions. Full color 3D molecular models throughout. Includes WileyPLUS online learning platform. 1300+ pages covering all major topics. Step-by-step SkillBuilder examples. Used in pre-med and chemistry programs. Extensive index and glossary.",
    price: 299.99,
    category: "Books",
  },
  {
    name: "Bone: The Complete Cartoon Epic by Jeff Smith, One-Volume Color Edition, 1300+ Pages, Award-Winning Fantasy Comic",
    brand: "Scholastic",
    description: "Complete Bone saga in single volume. Jeff Smith's award-winning fantasy adventure. Three Bone cousins lost in mysterious valley. Epic quest filled with humor and heart. Full-color edition with 1300+ pages. Winner of 10 Eisner Awards and multiple Harvey Awards. Suitable for readers of all ages. Features dragons, rat creatures, and mysterious forces. New York Times bestseller. Considered one of greatest graphic novels ever made.",
    price: 39.99,
    category: "Books",
  },
  {
    name: "Where the Crawdads Sing by Delia Owens, #1 New York Times Bestseller Mystery Novel, 384 Pages, Now a Major Motion Picture",
    brand: "Penguin Random House",
    description: "Coming-of-age tale set in North Carolina marshes. Murder mystery intertwined with love story. Over 18 million copies sold worldwide. #1 New York Times bestseller for years. 384 pages of evocative prose. Adapted into major motion picture. Explores themes of isolation and belonging. Beautiful nature writing combined with suspense. Perfect for readers who loved Educated. Book club favorite with discussion guide.",
    price: 15.99,
    category: "Books",
  },
  {
    name: "Thinking, Fast and Slow by Daniel Kahneman, Nobel Prize Winner's Guide to Decision-Making and Cognitive Biases, 499 Pages",
    brand: "Macmillan",
    description: "Daniel Kahneman's groundbreaking work on behavioral economics. Explores two systems of thinking: fast and slow. Reveals cognitive biases affecting our choices. Over 2 million copies sold. 499 pages of accessible psychology. Winner of National Academy of Sciences Best Book Award. Practical applications for business and life. Challenges assumptions about rationality. Essential reading for understanding human behavior.",
    price: 20.99,
    category: "Books",
  },

  // Toys & Games - Board games, video games, educational toys
  {
    name: "Catan Board Game, Classic Strategy Game of Trading and Building for 3-4 Players, Ages 10+, Winner of Spiel des Jahres",
    brand: "Catan Studio",
    description: "Build settlements, cities, and roads on island of Catan. Collect and trade resources with other players. Modular board creates different layouts each game. 3-4 players, ages 10 and up. Average playtime 60-120 minutes. Sold over 32 million copies worldwide. Gateway game perfect for new board gamers. Expansions available for variety. Encourages negotiation and strategic thinking. Winner of Spiel des Jahres award.",
    price: 44.99,
    category: "Toys & Games",
  },
  {
    name: "The Legend of Zelda: Tears of the Kingdom for Nintendo Switch, Epic Adventure with Open World Exploration, Physical Cartridge",
    brand: "Nintendo",
    description: "Sequel to Breath of the Wild expands Hyrule. Explore floating islands and underground depths. New abilities like Fuse and Ultrahand. Build vehicles and devices with creative freedom. Stunning visuals push Switch hardware limits. 50+ hours of main quest plus side content. Critics praise innovation and world design. Single-player adventure suitable for all ages. Physical cartridge or digital download available. Requires Nintendo Switch console.",
    price: 59.99,
    category: "Toys & Games",
  },
  {
    name: "LEGO Architecture Set, 1564-Piece Building Kit of Famous Landmark, Ages 16+, Display Model 12 inches Tall",
    brand: "LEGO",
    description: "Detailed recreation of iconic architectural masterpiece. 1564 pieces for engaging build experience. Includes informational booklet about structure. Display-worthy model approximately 12 inches tall. LEGO Architecture series celebrates design. Numbered bags organize building process. Suitable for ages 16 and up. Develops fine motor skills and patience. Perfect for architecture enthusiasts and LEGO fans. Makes impressive desk or shelf display.",
    price: 79.99,
    category: "Toys & Games",
  },
  {
    name: "Ticket to Ride Board Game, Award-Winning Train Strategy Game for 2-5 Players, Ages 8+, Family-Friendly",
    brand: "Days of Wonder",
    description: "Build railroad routes across North America. Collect train cards to claim routes between cities. Complete destination tickets for bonus points. 2-5 players, ages 8 and up. Plays in 30-60 minutes. Winner of multiple Game of the Year awards. Easy to learn, engaging for all skill levels. Beautiful illustrated board and components. Expansions add new maps and mechanics. Family-friendly competitive fun.",
    price: 49.99,
    category: "Toys & Games",
  },
  {
    name: "Elden Ring for PlayStation 5 and Xbox, Dark Fantasy Action RPG, Game of the Year 2022, Rated M for Mature",
    brand: "Bandai Namco",
    description: "From creators of Dark Souls and George R.R. Martin. Massive open world with intricate dungeons. Deep character customization and build variety. Challenging combat rewards skill and strategy. Stunning visuals and atmospheric soundtrack. 100+ hours of gameplay content. Multiplayer co-op and PvP features. Game of the Year winner 2022. Available for PlayStation, Xbox, and PC. Rated M for Mature audiences.",
    price: 59.99,
    category: "Toys & Games",
  },
  {
    name: "Learning Resources STEM Robotics Kit, 120+ Pieces with Motors and Sensors, Coding Interface for Ages 8-12",
    brand: "Learning Resources",
    description: "Build and code your own robots. 120+ pieces include motors, sensors, and connectors. Drag-and-drop coding interface teaches programming. Compatible with tablets and computers. 10 guided projects plus unlimited creativity. STEM learning through hands-on play. Develops problem-solving and critical thinking. Detailed instruction manual included. Award-winning educational toy. Requires 4 AA batteries (not included).",
    price: 69.99,
    category: "Toys & Games",
  },
  {
    name: "Pandemic Board Game, Cooperative Strategy Game for 2-4 Players, Ages 8+, Save the World from Diseases",
    brand: "Z-Man Games",
    description: "Work together to stop global disease outbreaks. 2-4 players with asymmetric character abilities. Plan strategies and make tough decisions as team. Plays in 45 minutes with variable difficulty. Award-winning cooperative gameplay. Multiple expansions add new challenges. Teaches planning, communication, and teamwork. Ages 8 and up. Highly replayable with changing board state. Named one of best board games ever made.",
    price: 39.99,
    category: "Toys & Games",
  },
  {
    name: "Nintendo Switch OLED Gaming Console with 7-inch OLED Screen, 64GB Storage, Enhanced Audio, Includes Dock and Joy-Con",
    brand: "Nintendo",
    description: "7-inch OLED screen with vivid colors and contrast. Play handheld, tabletop, or docked to TV. 64GB internal storage (expandable with microSD). Enhanced audio for handheld mode. Adjustable wide stand for tabletop play. Includes dock with wired LAN port. Joy-Con controllers detach for multiplayer. Access library of thousands of games. Up to 9 hours battery life. Backward compatible with Switch games.",
    price: 349.99,
    category: "Toys & Games",
  },
  {
    name: "Melissa & Doug Wooden Alphabet Puzzle, 26 Chunky Letters for Toddlers Ages 2-4, Develops Fine Motor Skills",
    brand: "Melissa & Doug",
    description: "26 colorful wooden letters stand upright. Thick pieces easy for little hands to grasp. Letters fit into matching puzzle board slots. Develops letter recognition and fine motor skills. Bright colors and familiar objects illustrated. Sturdy wood construction built to last. Non-toxic paints safe for young children. Ages 2-4 years. Encourages hand-eye coordination. Coordinates with other Melissa & Doug learning toys.",
    price: 19.99,
    category: "Toys & Games",
  },
  {
    name: "Wingspan Board Game, Bird-Themed Engine-Building Game with 170 Unique Cards, 1-5 Players, Winner of Kennerspiel des Jahres 2019",
    brand: "Stonemaier Games",
    description: "Attract birds to your wildlife preserve. 170 unique bird cards with beautiful artwork. Engine-building gameplay creates cascading combos. 1-5 players, ages 10 and up. Solo mode available with Automa opponent. 40-70 minute playtime. Winner of Kennerspiel des Jahres 2019. Educational with real bird facts. Includes dice tower birdfeeder. Expansions add birds from other continents. Relaxing theme with strategic depth.",
    price: 64.99,
    category: "Toys & Games",
  },
];
